/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <termio.h>
#include <malloc.h>
#include "node.h"
#include "Rsa.h"
#include <android/log.h>
#include <openssl/rsa.h>
#define TAG "democ"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,TAG,__VA_ARGS__)
#define OPENSSLKEY "test.key"
#define PUBLICKEY  "test_pub.key"
#define BUFFSIZE   1024
/* Header for class wc_ym_studyforc_Cmethod */
#ifndef _Included_wc_ym_studyforc_Cmethod
#define _Included_wc_ym_studyforc_Cmethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wc_ym_studyforc_Cmethod
 * Method:    method
 * Signature: ()Ljava/lang/String;
 */
jstring Java_wc_ym_studyforc_Cmethod_method(JNIEnv *env,jclass thiz){
     return (*env)->NewStringUTF(env,"SUCCESS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
}
jstring Java_wc_ym_studyforc_Cmethod_EncodeString(JNIEnv *env, jclass thiz, jstring str,jint length){
    const char *str_wait_decode = (*env)->GetStringUTFChars(env,str,0);//jstring转char*
    char *a[] = {"asdasd"};
    printLog(a);

    return (*env)->NewStringUTF(env,"encode");
}

jstring Java_wc_ym_studyforc_Cmethod_DecodeString(JNIEnv *env, jclass thiz, jstring str,jint length){
    return (*env)->NewStringUTF(env, "decode");
}
const char keyValue[] = {
        21, 25, 21, -45, 25, 98, -55, -45, 10, 35, -45, 35,
        26, -5, 25, -65, -78, -99, 85, 45, -5, 10, -0, 11,
        -35, -48, -98, 65, -32, 14, -67, 25, 36, -56, -45, -5,
        12, 15, 35, -15, 25, -14, 62, -25, 33, -45, 55, 12, -8
};

const char iv[] =  {    //16 bit
        -33, 32, -25, 25, 35, -27, 55, -12, -15, 23, 45, -26, 32, 5 - 2, 74, 54
};


jbyteArray Java_wc_ym_studyforc_Cmethod_getKeyValue(JNIEnv *env,jclass obj)
{
    jbyteArray kvArray = (*env)->NewByteArray(env, sizeof(keyValue));
    jbyte *bytes = (*env)->GetByteArrayElements(env,kvArray,0);

    int i;
    for (i = 0; i < sizeof(keyValue);i++){
        bytes[i] = (jbyte)keyValue[i];
    }

    (*env)->SetByteArrayRegion(env,kvArray, 0, sizeof(keyValue),bytes);
    (*env)->ReleaseByteArrayElements(env,kvArray,bytes,0);

    return kvArray;
}

//JNIEXPORT JNICALL
jbyteArray Java_wc_ym_studyforc_Cmethod_getIv(JNIEnv *env,jclass obj)
{

    jbyteArray ivArray = (*env)->NewByteArray(env, sizeof(iv));
    jbyte *bytes = (*env)->GetByteArrayElements(env,ivArray, 0);
    int i;
    for (i = 0; i < sizeof(iv); i++){
        bytes[i] = (jbyte)iv[i];
    }

    (*env)->SetByteArrayRegion(env,ivArray, 0, sizeof(iv), bytes);
    (*env)->ReleaseByteArrayElements(env,ivArray,bytes,0);

    return ivArray;
}

#ifdef __cplusplus
}
#endif
#endif

