/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wc_ym_studyforc_Cmethod */

#ifndef _Included_wc_ym_studyforc_Cmethod
#define _Included_wc_ym_studyforc_Cmethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wc_ym_studyforc_Cmethod
 * Method:    method
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wc_ym_studyforc_Cmethod_method
  (JNIEnv *, jclass);

/*
 * Class:     wc_ym_studyforc_Cmethod
 * Method:    EncodeString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wc_ym_studyforc_Cmethod_EncodeString
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     wc_ym_studyforc_Cmethod
 * Method:    DecodeString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wc_ym_studyforc_Cmethod_DecodeString
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     wc_ym_studyforc_Cmethod
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_wc_ym_studyforc_Cmethod_getIv
  (JNIEnv *, jclass);

/*
 * Class:     wc_ym_studyforc_Cmethod
 * Method:    getKeyValue
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_wc_ym_studyforc_Cmethod_getKeyValue
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
